import 'package:projet_listes/place.dart';

class DataSource {
  List<Place> allPlaces() {
    return [
      Place(
          name: "Chambéry",
          imagePath: "chambery",
          desc:
              "Capitale historique de la Savoie, Chambéry est une ville d'Art et d'Histoire dévoilant de nombreux atouts. La vieille ville, admirablement restaurée, invite le promeneur à découvrir ses allées mystérieuses aux multiples passages couverts, ses hôtels particuliers, ses façades en trompe-l'oeil, ses charmantes cours intérieures, sa cathédrale Saint-François-de-Sales renfermant des peintures en trompe-l'oeil, son château, ancienne résidence des comtes et ducs de Savoie, ses rues piétonnes et sa célèbre fontaine des Éléphants. La visite se poursuit avec le musée Savoisien, exposant des collections archéologiques et ethnographiques, et le musée des Beaux-Arts abritant un grand nombre de peintures italiennes. La place Saint-Léger, fort animée, est un lieu incontournable de la ville pour se balader et flâner à la terrasse d'un café. La ville propose également un grand nombre d'évènements culturels, avec l'espace André Malraux, situé dans le quartier Curial, et le théâtre Charles Dullin."),
      Place(
          name: "La raclette",
          imagePath: "raclette",
          desc:
              "La Raclette de Savoie a obtenu une indication géographique protégée (IGP), le 27 janvier 2017. Les opérations de production du lait, de transformation et d’affinage ont lieu dans l’aire géographique délimitée, qui comprend la totalité des communes des départements de Savoie et de Haute-Savoie, et quelques communes limitrophes de l’Ain et de l’Isère. Le lait provient essentiellement de vaches de races : Abondance, Montbéliarde ou Tarentaise. L’alimentation des vaches repose principalement sur des fourrages verts. Le nombre opérateur en 2016 est de : 659 producteurs laitiers ; 6 producteurs fermiers ; 1 transformateur ; 5 affineurs et 8 transformateurs-affineurs. Sa période de dégustation optimale s'étale d'octobre à décembre après un affinage de 4 à 5 mois, mais il se déguste également d'août à avril."),
      Place(
          name: "Saint-Genix-sur-Guiers",
          imagePath: "genix",
          desc:
              "Saint-Genix-sur-Guiers est une ancienne commune française située dans le département de la Savoie, en région Auvergne-Rhône-Alpes. Le 1er janvier 2019, elle a fusionné avec les communes de Gresin et Saint-Maurice-de-Rotherens pour former la commune nouvelle de Saint-Genix-les-Villages. Saint-Genix-sur-Guiers est à la fois la commune la plus occidentale et la moins élevée du département de la Savoie. Sous influence de la métropole lyonnaise, elle se situe d'ailleurs à 80 kilomètres à l'est de Lyon, et est la commune savoyarde la plus proche de l'aire urbaine de Lyon, qui commence quelques kilomètres à l'ouest aux Avenières. La commune se situe à la confluence du Rhône et du Guiers, au carrefour des départements de Savoie, de l'Isère et de l'Ain, qui domine le Rhône par l'extrémité sud du Bugey."),
      Place(
          name: "Grande Casse",
          imagePath: "grande-casse",
          desc:
              "La Grande Casse est le plus haut sommet du massif de la Vanoise, dans les Alpes françaises, et du département de la Savoie. La Grande Casse se trouve dans le département français de la Savoie, à cheval sur les communes de Pralognan-la-Vanoise à l'ouest, de Champagny-en-Vanoise au nord et de Val-Cenis au sud. La station de Tignes se trouve en direction du nord-ouest. Avec ses 3 855 mètres d'altitude, elle constitue le point culminant du massif de la Vanoise, dans les Alpes, et le plus haut sommet du département. Elle se trouve sur la même arête que la Grande Motte (3 653 m) à l'est et n'est séparée de la pointe Mathews (3 783 m) que par le col des Grands Couloirs au sud-ouest. Cette crête constitue la ligne de partage des eaux entre les vallées de la Tarentaise au nord et de la Maurienne au sud. Elle domine également des sommets environnants comme le Grand Bec (3 399 m), la pointe du Vallonnet (3 371 m), les pointes et aiguille de l'Épéna (3 421 m pour cette dernière), la pointe de la Sana (3 436 m) ou encore le mont Pelve (3 260 m). Le versant ouest du sommet abrite le glacier des Grand Couloirs, son versant nord-ouest le glacier de la Grande Casse et son versant nord-est le glacier de Rosolin."),
      Place(
          name: "Massif des Bauges",
          imagePath: "bauges",
          desc:
              "Le massif des Bauges, ou plus communément les Bauges, est un massif montagneux calcaire des Préalpes françaises du nord, se situant à cheval sur les départements de la Savoie et de la Haute-Savoie et culminant à plus de 2 200 mètres d'altitude. Il constitue une région naturelle. Le cœur du massif forme le pays des Bauges, façonné par l'élevage laitier traditionnel, alors que les pentes externes du massif appartiennent historiquement aux versants des grandes vallées environnantes. Tant par la richesse de la faune que par celle de la flore, le patrimoine naturel est remarquable et constitue l'un des atouts majeurs du parc naturel régional du massif des Bauges créé en 1995. Depuis les années 1990, le massif des Bauges, entouré de villes dynamiques (Annecy, Aix-les-Bains, Chambéry, Albertville), bénéficie d'investissements, attire une nouvelle population et se repeuple légèrement. Les natifs et habitants des Bauges s'appellent les Baujus."),
      Place(
          name: "Massif de la Chartreuse",
          imagePath: "chartreuse",
          desc:
              "Le massif de la Chartreuse est un massif montagneux des Préalpes, situé en majeure partie dans le département français de l'Isère et aussi dans celui de la Savoie, constituant une région naturelle. Il culmine à 2 082 mètres d'altitude à Chamechaude. Il est constitué essentiellement de calcaires disposés en successions d'anticlinaux et de synclinaux formant de longues lignes de crêtes orientées du nord au sud. Les dépressions, au fond desquelles coulent le Guiers et ses affluents, sont séparées par des cols. Le massif, soumis à un climat océanique montagnard, connaît des précipitations relativement importantes mais l'eau est peu présente en surface ; elle s'écoule rapidement dans les réseaux karstiques creusés dans le calcaire. La création du parc naturel régional de Chartreuse a permis de dynamiser le tourisme, de valoriser le patrimoine culturel, tout en préservant l'environnement grâce à la gestion du territoire. Il est complété par la réserve naturelle nationale des Hauts de Chartreuse afin de préserver la biodiversité. Le milieu naturel se partage entre les forêts de feuillus et de conifères, les espaces herbacés, les falaises et de rares zones humides en périphérie du massif, abritant de nombreuses espèces protégées."),
      Place(
          name: "Massif du Beaufortain",
          imagePath: "beaufortain",
          desc:
              "Le massif du Beaufortain est un massif des Alpes françaises situé à cheval sur les deux départements de Savoie. Il est limité par l'Isère (vallée de la Tarentaise) au sud, l'Arly au nord-ouest et le Bon-Nant au nord-est. Il est également parcouru par la rivière Dorinet puis Doron de Beaufort du nord-est au sud-ouest, au niveau de Beaufort, et leurs affluents, ce qui compartimente le massif. Il est entouré de la chaîne des Aravis, du massif des Bauges, du massif de la Lauzière, du massif de la Vanoise et du massif du Mont-Blanc. Le massif du Beaufortain appartient au domaine des massifs cristallins externes dans sa partie occidentale et possède une couverture sédimentaire dans la zone orientale (zone la plus élevée), la limite se situant autour du col de la Louze sur une ligne longeant la vallée de la Glaize, entre La Léchère et Arêches, puis se prolongeant de Beaufort au massif du Mont-Blanc en passant par la vallon de la Gittaz."),
      Place(
          name: "Massif du Mont-Blanc",
          imagePath: "mt-blanc",
          desc:
              "Le massif du Mont-Blanc est un massif des Alpes partagé entre la France, l'Italie et la Suisse. Il abrite le mont Blanc, plus haut sommet d'Europe occidentale qui culmine à 4 808 mètres. Il est traversé par le tunnel du Mont-Blanc, entre Chamonix dans la vallée de l'Arve et Courmayeur dans la vallée d'Aoste. Ce massif est relativement restreint en superficie puisqu'il s'étend sur seulement 400 km2 environ, mais il empiète sur trois pays : il est situé en grande partie sur le département français de la Haute-Savoie, mais également de la Savoie, sur la Vallée d'Aoste en Italie et sur le canton du Valais en Suisse. Il est entouré des aiguilles Rouges au nord-ouest (rive droite de l'Arve), du massif du Giffre au nord, des Alpes pennines à l'est, des Alpes grées au sud-est et du massif du Beaufortain au sud-ouest. Il est formé d'une chaîne principale allant des Clochers d'Arpette au nord en Suisse au mont Tondu au sud en France en passant par le mont Blanc au centre à la frontière franco-italienne et qui comporte les plus hauts sommets, notamment ceux dépassant les 4 000 mètres d'altitude. D'autres sommets secondaires l'entourent comme le Catogne, le mont de l'Arpille et la montagne de Balme au nord, le Prarion à l'ouest, les têtes de Bellaval, la tête Nord des Fours, la crête des Gittes et le rocher du Vent au sud-ouest ainsi que tout le chaînon montagneux entre les cols de la Seigne et du Petit-Saint-Bernard avec le Monte Berio Blanc, la montagne de la Seigne, les Grandes Aiguilles et le sommet des Rousses au sud-est. Le cœur du massif, du fait de son altitude et du petit nombre de vallées l'entrecoupant, est inhabité. En effet, les glaciers occupent les dépressions jusque bas dans les vallées, et les torrents qu'ils alimentent ne suffisent pas à éroder le massif. Il est entouré par la vallée de l'Arve à l'ouest, et à l'est par une succession de vallons longeant parallèlement le massif : du nord au sud, la vallée du Trient et le val Ferret suisse en Valais, le val Ferret italien et val Vény dans la vallée d'Aoste et enfin la vallée des Glaciers en Savoie"),
      Place(
          name: "Aix-les-Bains",
          imagePath: "aix",
          desc:
              "Aix-les-Bains est une station thermale située au bord du lac du Bourget, en Savoie, dans l'est de la France. La baignade, la voile et le golf y sont souvent pratiqués. La ville possède plusieurs monuments emblématiques tels que les vestiges romains du temple de Diane, jouxtant la mairie, et le château de la Roche du Roi, de style Belle Époque. Datant du XIIe siècle, l'abbaye d'Hautecombe, sur la rive opposée du lac, abrite une nécropole royale. À proximité, le mont Revard offre des sentiers de VTT, et des pistes de ski alpin et de ski de fond. Importante cité à la Belle Époque de renommée internationale, Aix-les-Bains fut un lieu majeur de villégiature pour les familles princières ou fortunées. Les sources thermales en firent une station des plus réputées au monde. Grâce à son centre historique et à plusieurs lieux ou monuments inscrits ou classés au titre des monuments historiques, la commune est labellisée Ville d'art et d'histoire. Par ailleurs, Aix est implantée en bordure du plus grand lac naturel d'origine glaciaire de France et possède ainsi le plus grand port de plaisance en eau douce français."),
      Place(
          name: "Albertville",
          imagePath: "albertville",
          desc:
              "Albertville (savoyard : Arbèrtvela) est une commune française située dans le département de la Savoie en région Auvergne-Rhône-Alpes. La ville tient son nom du roi de Sardaigne Charles-Albert de Savoie-Carignan, fondateur de la ville dans la première moitié du xixe siècle. Située au cœur des Alpes, la commune se trouve à la confluence de l'Isère et de son affluent l'Arly, marquant également la jonction des vallées de la Tarentaise, du Beaufortain et du val d'Arly, en amont de la combe de Savoie. Cette situation géographique lui vaut actuellement le surnom de Carrefour des Quatre Vallées. Sa situation géographique et ses atouts montagnards permirent à la ville d’accueillir les XVIe Jeux olympiques d'hiver de 1992 même si la plupart des épreuves se déroulaient dans les nombreuses stations alentour. La commune d'Albertville se trouve aux portes de plusieurs vallées alpines du département de la Savoie. Elle est en effet située à la limite de la Tarentaise, du Beaufortain et du val d'Arly, en amont de la combe de Savoie. Albertville s'est développé sur le cours de la rivière Arly, avant sa jonction avec l’Isère, situé en partie au sud-ouest de la commune. Les massifs alentour sont pour leur part les Bauges (à l'ouest), le Beaufortain (au nord), la Lauzière (au sud) et le Grand Arc. Les sommets observables depuis Albertville sont la Belle Étoile, la dent de Cons, la Négresse, la roche Pourrie, le Mirantin, la pointe de la Grande Journée et la chaîne du Grand Arc."),
      Place(
          name: "Tomme de Savoie",
          imagePath: "tomme",
          desc:
              "De l'ancien provençal « toma », du latin populaire « toma » (« fromage gras »), du celtique « tom » (« masse »). Tomme de Savoie est l'appellation d'origine d'un fromage produit en France dans la région alpine de Savoie, regroupant les départements de la Savoie et de la Haute-Savoie. À l'origine élaborée par les familles paysannes pour leur subsistance, la tomme est aussi sans doute le plus ancien des fromages de Savoie. Il fait partie du patrimoine économique et culturel des deux départements. Quand les fromages sont destinés au commerce, ils arborent la marque de certification « Savoie »; depuis 1996, l'utilisation de l'appellation tomme de Savoie est soumise aux conditions énoncées dans le cahier des charges du label officiel de l'Union européenne Indication géographique protégée (IGP). Sa période de consommation idéale s'étend d'août à février."),
      Place(
          name: "Tartiflette",
          imagePath: "tartiflette",
          desc:
              "La tartiflette (dérivé de tartifle ou tartiflâ, pomme de terre en savoyard) est une recette de cuisine à base de gratin de pommes de terre, d'oignons et de lardons, le tout gratiné au reblochon (fromage AOP des pays de Savoie). D'origine récente (le plat a été inventé dans les années 1980), la recette est devenue l'un des emblèmes de la cuisine française, y compris à l'étranger. La « tartiflette au reblochon ou reblochon de Savoie » obtient un Label rouge le 9 octobre 2014 : pour être certifié Label rouge, l'AOP Reblochon de Savoie doit être le seul fromage du plat et constituer au minimum 20 % de la recette1. De plus, le produit doit être gratiné au four traditionnel. Pour préparer une tartiflette, les pommes de terre sont précuites (à l'eau, à la vapeur ou, de préférence, à la poêle) et épluchées. Séparément, on fait revenir des oignons et des lardons. On coupe ensuite des reblochons en deux par la tranche et on les dispose croûte vers le bas ou croûte vers le haut (selon les écoles) sur le dessus du plat. Le plat peut être agrémenté d'un peu de vin blanc sec du vignoble de Savoie (Apremont (AOC), Chignin (AOC), Savoie (AOC)2…). Le vin peut servir pour déglacer les oignons, ou autres variantes possibles. Prendre un reblochon bien fait et placer le plat au four jusqu'à ce que le reblochon soit fondu et que sa croûte soit grillée. La tartiflette peut se déguster avec un vin du vignoble de Savoie (vin blanc, Chignin-bergeron ou d'un vin rouge fruité, par exemple…)."),
      Place(
          name: "Crozets",
          imagePath: "crozets",
          desc:
              "Les crozets sont une spécialité de la Savoie à base de petits morceaux de pâte, aplatie au rouleau et coupée en carrés à l'aide d'un couteau-hachoir spécifique. Le nom viendrait du franco-provençal savoyard croé qui signifie « petit1 » ; d'autres pensent qu'il proviendrait du bas latin crux, qui signifie « croix » et qui a donné le savoyard crwê, mais on trouve aussi différents termes comme croêze, croêju (Albertville), croezu (Annecy), croezet (Thônes), krozè (Oisans). À noter aussi la ressemblance de nom avec les croxetti (en) (ou corzetti), des pâtes italiennes dont l'appellation provient de la petite croix gravée sur leur face. Il existe aussi une croyance selon laquelle le nom de crozet serait dérivé du patronyme d'un certain docteur B. Croizat qui se trouvait démuni face à une de ses patientes manifestant une tendance hypocondriaque. Pour la soulager de ses douleurs, il décida de lui mentir en lui présentant ce nouveau mets tout en lui assurant qu'il s'agissait d'un remède puissant si l'on en mangeait en quantité raisonnable. Cette légende ne fait toutefois pas consensus et on lui préfère souvent l'explication du précédent paragraphe."),
      Place(
          name: "Diot",
          imagePath: "diots",
          desc:
              "Un diot (prononcé [djo]) est une saucisse savoyarde, traditionnelle de la cuisine savoyarde. Déclinée de diverses façons : nature, pur porc, fumé, aux choux, au beaufort, elle est généralement cuisinée avec des oignons et du vin du vignoble de Savoie, et servie avec des tartifles (pomme de terre, en savoyard). Le mot français « diot » vient directement du dialecte savoyard, où le mot diot ou diau signifie une petite saucisse, voire les saucisses en général. Ce terme se rencontre principalement dans la cluse chambérienne, dans le massif des Bauges, le pays de l'Albanais, la combe de Savoie et dans les grandes vallées de Maurienne et de Tarentaise. Il existe une fausse étymologie qui relie l'origine du nom avec le mot Sabaudia qui donnera par la suite le mot Savoie, mais qui aurait pu donner par contraction Diot ou Diau, ou même directement avec le mot Dieu. L'expression « saucer les/le diot(s) » signifie préparer ce type de saucisses avec de la sauce."),
      Place(
          name: "Fondue Savoyarde",
          imagePath: "fondue",
          desc:
              "La fondue savoyarde est un plat régional de la gastronomie savoyarde à base de fromage fondu et de pain. Elle est préparée à base de 3 fromages, à partir de produits locaux tels que le comté de montagne, le beaufort, le gruyère de Savoie, l'emmental de Savoie ou encore l'abondance. Avec l'essor des sports d'hiver et du tourisme alpin depuis les années 1950, la fondue savoyarde est devenue une recette de cuisine populaire en France. L'historienne Marie-Thérèse Hermann relève que la fondue ne fait pas partie de la culture traditionnelle savoyarde, mais qu'elle s'est développée au lendemain de la Seconde Guerre mondiale en Savoie. Seule la partie nord, frontalière avec la Suisse, connaissait ce plat. Toutefois, en raison du coût de celui-ci, il était peu répandu. Les paysans pouvaient à l'occasion passer un morceau de fromage sur le feu et le mangeaient avec du pain. Ce mets fait partie avec le berthoud, les croûtes au fromage et la poêlée montagnarde des principales recettes de la cuisine savoyarde nécessitant des fromages à pâte pressée cuite et du vin blanc."),
      Place(
          name: "Beaufort",
          imagePath: "beaufort",
          desc:
              "Beaufort est l'appellation d'origine d'un fromage au lait cru de vache, à pâte pressée cuite, élaboré en Savoie en France. La production du lait et sa transformation s'effectuent dans une aire comprenant la région du Beaufortain d'où il tire son nom1. Il est formé en meule à talon légèrement concave. L'appellation beaufort est préservée commercialement via une Appellation d'origine protégée. Autrefois, le volume produit par un grand nombre de producteurs fermiers était important, puis il a payé un lourd tribut à l'exode rural et aux contraintes spécifiques de production laitière qui étaient mal valorisées. Son appellation a été préservée dès 1968 via une AOC. Il est aujourd'hui un des représentants de la cuisine savoyarde : de la fondue savoyarde au gratin de crozets, le beaufort est présent sur de nombreuses tables de lieux touristiques du pays. Les Ceutrons, peuple celte, occupent la région. Pline cite leur fromage, le vatusicum, produit grâce au lait de petites vaches. La région est annexée à l'Empire romain vers 20 av. J.-C. Un domaine appartenant à un certain Lucius aurait existé dans le Beaufortain : la vallée portait le nom de Luciaco ou Villa lucia au Moyen Âge et Hauteluce pourrait aussi en provenir."),
      Place(
          name: "Courchevel",
          imagePath: "courchevel",
          desc:
              "Courchevel est une station de sports d'hiver de la vallée de la Tarentaise située dans la commune de Courchevel (jusqu'en 2016, la commune de Saint-Bon-Tarentaise), dans le département de la Savoie en région Auvergne-Rhône-Alpes. Première station française aménagée en site vierge en 1946, elle fait partie du domaine skiable des Trois Vallées. La station est organisée autour de cinq villages : Saint-Bon-Tarentaise (chef-lieu communal), Courchevel Le Praz (appelé avant 2011 Courchevel 1300), Courchevel Village (anciennement Courchevel 1550), Courchevel Moriond (anciennement Courchevel 1650) et enfin Courchevel (anciennement Courchevel 1850). Ce dernier, qui donne son nom à la station, est le premier noyau de développement où s'applique le travail de l'architecte urbaniste Laurent Chappis et de l'ingénieur Maurice Michaud. Cette nouvelle urbanisation de la montagne a fait l'objet d'une inscription à l'inventaire supplémentaire des monuments historiques en 1998, et une trentaine de sites sont protégés au titre des monuments historiques. La station ne se limite pas à la seule saison hivernale et ses pratiques du ski, elle s'est équipée notamment d'infrastructures collectives de loisirs et sportives, comme un centre aqualudique ouvert en décembre 2015, et propose d'autres pratiques en lien avec la montagne durant l'été, avec la randonnée ou le VTT, mais aussi son festival international d'art pyrotechnique ou encore l'organisation d'exposition d'art contemporain. Après avoir été un lieu d'hébergement et le théâtre d'épreuves sportives des Jeux Olympiques d'hiver d'Albertville 1992, Courchevel accueillera, conjointement avec Méribel, les Championnats du monde de ski alpin 2023. "),
      Place(
          name: "Fontaine des Eléphants",
          imagePath: "fontaine",
          desc:
              "La fontaine des Éléphants, historiquement appelée la colonne de Boigne et aujourd'hui plus simplement appelée « les Éléphants » ou surnommée « les quatre sans culs », est une fontaine située dans la commune de Chambéry, dans le département français de la Savoie en région Auvergne-Rhône-Alpes. Érigée en 1838 en l'honneur du général-comte de Boigne, la fontaine est aujourd'hui l'un des plus célèbres monuments de la ville. L’ensemble, haut de 17,65 mètres et bâti en pierre calcaire de Saint-Sulpice, est une habile superposition de trois monuments : une fontaine, une colonne et une statue. La fontaine présente dans son plan la croix de Savoie. Quatre éléphants réunis par la croupe, réalisés en fonte de fer, jettent l’eau par leurs trompes dans un bassin octogonal et portent chacun une tour de combat surmontée d’un bas-relief ou d’une inscription. Sur les éléphants, se dresse une grande colonne, symbolisée par un tronc de palmier. Sa base est ornée d'une grande variété de trophées : « Des armes persanes, mogholes, hindoues ; divers objets rappelant les mœurs, les arts et la civilisation des peuples que le général de Boigne a combattus ou gouvernés, composent les trophées ». Le sommet de la colonne est constitué d'une statue du général-comte de Boigne à qui le monument est dédié. Ce dernier est vêtu de son costume de lieutenant-général du royaume de Sardaigne. Son manteau relevé sur son épaule gauche laisse apparaître sa main posée sur un sabre oriental, tandis que sa main droite tient un document sur lequel est inscrit « dons à la Ville de Chambéry », représentant l'ensemble des donations accordées à la ville par le comte de Boigne. Il s'agit d'une statue en bronze fondue à Paris dans les ateliers de Charles Crozatier. Elle pèse 750 kg et mesure 2,82 m de hauteur."),
      Place(
          name: "Château des Ducs de Savoie",
          imagePath: "chateau",
          desc:
              "Le château des ducs de Savoie est situé à Chambéry, en Savoie. Il a été édifié à partir du XIe siècle, et plusieurs fois agrandi et remanié. Depuis 1860, année de la réunion de la Savoie à la France, il abrite la Préfecture et le Conseil départemental. Jusqu'alors, il était à la fois résidence des comtes puis ducs de Savoie et siège de différentes entités administratives. L'édifice présente la forme d'un quadrilatère dont se détache un donjon carré, lui-même flanqué de tours et d'une chapelle. Dans l'aile médiévale, les différentes salles de l'ancienne Chambre des comptes abritent une exposition permanente retraçant l'histoire du château, classé Monument Historique depuis le XIXe siècle. Cet endroit est en accès libre toute l'année. Les autres parties remarquables du château ne sont en revanche ouvertes au public que lors de visites guidées (et donc payantes). On peut découvrir à cette occasion, outre la Chambre des comptes, la cour d'honneur, ou encore la Tour Trésorerie : elle date du XIIIe siècle et présente une forme polygonale et est dotée d'éléments défensifs. Jalonne également le circuit, la Sainte-Chapelle, élevée au XVe pour remplacer la chapelle primitive devenue exiguë. Sa nef unique est prolongée par une abside à cinq pans. Son décor relève du style gothique flamboyant. On remarque que le chevet s'appuie sur une courtine, et jouxte un chemin de ronde doté de créneaux et mâchicoulis restauré en 1895. La façade de cette Sainte-Chapelle a été remaniée en 1641, présentant désormais un décor classique. De 1502 à 1578, le célèbre Saint Suaire aujourd'hui conservé à Turin fut abrité dans cette chapelle. Enfin, une tour demi-ronde et la salle du Conseil départemental complètent la visite."),
      Place(
          name: "Cathédrale Saint-François-de-Sales",
          imagePath: "cathedrale",
          desc:
              "Édifiée au XVe siècle par les franciscains sur le territoire de Chambéry, en Savoie, la cathédrale Saint-François-de-Sales prend place au cœur du centre historique de la ville, entre la place Saint-Léger et la rue de la Croix-d'Or. Classé aux Monuments Historiques, ce bâtiment de style gothique flamboyant est devenu cathédrale en 1779, avant de devenir métropole en 1817. Sa façade révèle la modestie franciscaine, dévoilant une austérité qui ne manque cependant pas de charme. L'intérieur est quant à lui plus impressionnant, avec notamment un grand nombre de peintures en trompe-l'œil qui recouvrent les murs et les voûtes de la cathédrale. Ces dernières sont réalisées dans la première moitié du XIXe siècle dans un style gothique troubadour très apprécié à l'époque dans cette partie de la France. Les amateurs de belles pièces apprécieront l'orgue romantique de 1847 classé aux Monuments Historiques à titre d'objet, ou encore la réplique du Saint Suaire exposée depuis 2010."),
    ];
  }
}
